global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'rabbitmq_server_level'
    static_configs:
        # set the ip of the server where NodeExporter was Installed. 9100 is the NodeExporter port
      - targets: ['130.1.1.1:9100'] 
  - job_name: 'rabbitmq_app'
    static_configs:
       # set the ip of the server where RabbitMQ container is runnig. 15692 is the mertics port as defined in the docker compose file
       - targets: ['130.1.1.1:15692']